<?php

namespace AppBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPendingStatus()
    {
        return $this->findBy(
            array('status' => 'Oczekuje na wpłatę'),
            array('orderTime' => 'ASC')
        );
    }

    public function findByUser($user)
    {
        return $this->findBy(array(
            'userId' => $user
        ));
    }
}
