<?php

namespace AppBundle\Repository;

/**
 * OrderedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findById($orderId)
    {
        return $this->findBy(array(
            'orderId' => $orderId
        ));
    }

    public function findByReservation($ordersIds, $productIds)
    {
        return $this->findBy(
            array(
                'orderId' => ($ordersIds),
                'productId' => ($productIds),
                'productStatus' => array('Towar częściowo zarezerwowany', 'Brak towaru, oczekuje na dostawę')
            )
        );
    }
}
