parameters:

services:
  orderservice:
    class: AppBundle\Utils\OrderManager
    arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

  orderedproductservice:
    class: AppBundle\Utils\OrderedProductsManager
    arguments: ["@doctrine.orm.entity_manager", "@products"]