parameters:

services:
  app.order.service:
    class: AppBundle\Utils\OrderManager
    arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

  app.ordered.products.service:
    class: AppBundle\Utils\OrderedProductsManager
    arguments: ["@ordered.products"]

  app.order.from.cart.service:
    class: AppBundle\Utils\CartManager
    arguments: ["@cart", "@doctrine.orm.entity_manager"]


## ENTITIES:
  ordered.products:
    class: AppBundle\Entity\OrderedProducts

  cart:
    class: AppBundle\Entity\Cart
    arguments: ["@user", "@products"]

  user:
    class: AppBundle\Entity\User

  products:
    class: AppBundle\Entity\Products